config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/wedding_party', to: 'static_pages#wedding_party'
  get '/hotels', to:'static_pages#hotel_blocks'
  get '/hindu_weddings', to:'static_pages#hindu_weddings'
  get '/registry', to: 'static_pages#registry'
  get '/tourism', to:'static_pages#things_to_do'
  get '/schedule_of_events', to: 'static_pages#schedule_of_events'
  get '/our_family', to: 'static_pages#our_family'
  get '/information', to: 'static_pages#information'
  get '/rsvp', to: 'static_pages#rsvp'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # http_basic_authenticate_with :name => "your_name", :password => "your_password", only: :home

  def hello
    render html: "We're getting married!"
  end

  def goodbye
    render html: "Thanks for visiting!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def tourism
  end

  def registry
  end

  def wedding_party
  end

  def our_family
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.6.1/css/tachyons.min.css"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    body {
        font-family: "Lato", sans-serif;
    }

    .sidenav {
        height: 100%;
        width: 0;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        transition: 0.5s;
        padding-top: 60px;
    }

    .sidenav a {
        padding: 8px 8px 8px 32px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        display: block;
        transition: 0.3s;
    }

    .sidenav a:hover, .offcanvas a:focus{
        color: #f1f1f1;
    }

    .sidenav .closebtn {
        position: absolute;
        top: 0;
        right: 25px;
        font-size: 36px;
        margin-left: 50px;
    }

    #main {
        transition: margin-left .5s;
        padding: 16px;
    }

    @media screen and (max-height: 450px) {
      .sidenav {padding-top: 15px;}
      .sidenav a {font-size: 18px;}
    }
    </style>
  </head>

  <body>
    <%= yield %>
    <div id="sideNavigation" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a><%= link_to "Home", home_path %>
      <a><%= link_to "About Us", about_path  %>
      <a><%= link_to "Remington?!", our_family_path %>
      <a><%= link_to "Wedding Party", wedding_party_path  %>
      <a><%= link_to "Schedule of Events", schedule_of_events_path  %>
      <a><%= link_to "Hindu Weddings", hindu_weddings_path %>
      <a><%= link_to "Hotel Blocks & Other Important Info", hotels_path  %>
      <a><%= link_to "Registry", registry_path  %>
      <a><%= link_to "Things to do in Chicago", tourism_path  %>
      <a><%= link_to "RSVP", rsvp_path %>
    </div>

    <script>
      function openNav() {
        document.getElementById("sideNavigation").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
      }

      function closeNav()  {
        document.getElementById("sideNavigation").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
      }

    </script>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About the lovebirds!") %>
<body id="aboutus">
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
    <p class="pv4-l center pl4">
      <span style="font-size:60px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>
  <div class="tc pa5 code">
      <hr>
      <h2 class="upcase">Our Story</h2>

      <body>
      <p>Kathryn hails from the East Coast and made her way to Chicago after being accepted into graduate school at the University of Chicago. She stayed for the summers and amazing friends who became family, and the life she is building with the love of her life.</p>
      <p>Dushyant spent the majority of his life on the West Coast before finding himself without a jacket in Chicago after taking a job with Capital One (COF). He stayed because obviously its better to experience seasons, and he met the love of his life.</p>

      <hr>
      <h2 class="upcase">Meet Cute</h2>

      <p>As is now evident, we met at work! Eek! Dushyant and Kathryn met when they both joined software engineering teams at Capital One and their fate was sealed at a beerfest. A while later, Dushyant asked Kathryn on a date at the Purple Pig to which she (SPOILER) agreed. Dushyant ordered a steak well-done, Kathryn stopped and corrected him, and now they're getting married! </p>

      <hr>
      <h2 class="upcase">The Proposal</h2>

      <p>It all started easy enough, Dushyant was headed out of town with Trevor on a golf trip, Kathryn was headed to the 'burbs to hang out with some COF friends for the night. Things were going swimmingly until Natalia (love you girl!) made the unfortunate mistake of asking Kathryn where Dushyant was that night. With a twinkle in her eyes, Kathryn responded "oh! its so cute! Dushyant and Trevor are driving to WI and back, golfing along the way!" which made Natalia stop in her tracks. Not wanting to alarm Kathryn, she proceeded carefully, "Hm, Trevor was at work today..." to which Kathryn was convinced Natalia was just confusing Trevor with everyone other white male that works in tech. However, Natalia and Trevor have met and she was not mistaken. Trevor was indeed at work and not wth Dushyant...</p>

      <p>With alarm, Kathryn, knowing in the back of her mind she shouldn't push it but needing to solve the puzzle, called Dushyant, "Kanna, where are you? Where is Trevor?". Dushyant did his best attempt to mimic Trevors distinct voice and manner of speak, but Kathryn was not convinced. Dushyant just started laughing, surprised he made it this far into the surprise, and just said simply, "Im hanging up, Ill send you a picture. You'll laugh. See you tomorrow. I love you". And with that, the picture came in - a picture of her parents dogs and her parents. Kathryn, in complete shock, fell to the floor crying tears of happiness and confusion. How did he get those pictures?! Is he in NEW JERSEY!? How?!</p>

      <p>Alas, Dushyant had secretly flown to NJ to spend a weekend golfing with Kathryn's parents and asking for their blessing to join the family. In IL, Kathryn was given strict instructions to follow upon returning home from the suburbs. Under the mattress was a stack of sticky notes with a scavengar hunt. Kathryn found the dress she wore on their first date, got ready, completed the clues, and ultimately hailed a cab to...the <strong>Purple Pig</strong>. There, Duhsyant waited at the end of the high tables with a smile, a kiss, and some choice words that would forever change their life. </p>
      </p>
  </div>
</body>

app/views/static_pages/help.html.erb
<% provide(:title, "Help!") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/hindu_weddings.html.erb
<% provide(:title, "Kat & Dush") %>
<body>
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
  </div>
    <p class="pv4-l center pl4">
      <span style="font-size:60px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>
  <hr>
<h2>I've never been to a Hindu ceremony before - what do I need to know?</h2>

<h4>Here are some things to keep in mind before and while attending</h4>

<ul>Please refrain from wearing the following colors:
  <li>White - this color is reserved for funerals in the Hindu culture, as well as for the bride in America</li>
  <li>Red - this color is reserved for the bride in Hindu culture</li>
  <li>{{wedding party colors}}</li>
</ul>

<h4>Sarees, lenghas, (male outfit), oh my!</h4>

<p>While not required, we hope you will join us in celebrating Hindu traditions by wearing a saree or lengha (for women) or {{}} (for men). The wedding party and family will also be in traditional South Indian garb.</p>

<p>{{ Origin of outfits, any significance }} </p>

<p>If you need help picking an outfit, please do not hesitate to reach out to Kathryn or Dushyant and we can help you find the closest store!</p>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, 'Kat & Dush') %>
<title>Kat &amp Dush </title>
<body id="home">
  <link href="https://addtocalendar.com/atc/1.5/atc-style-blue.css" rel="stylesheet" type="text/css">
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
    <p class="pv4-l center pl4">
      <span style="font-size:60px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>
  <div style="width: 95%; font-family:cursive; letter-spacing: 3px;" class="tc white ma4 home-image">
    <img src="homedance.jpg" style="height:750px" alt=""/>
      <h1 class="ttu">Kathryn & Dushyant</h1>
      <h2 class="home-date">December 15, 2018</h2>
      <h2 class="home-tag">#NotAShotgunWedding</h2>
  </div>
  <div id="main" class="">
    <article class="pb5">
        <div class="tc fw3" style="font-family:cursive; letter-spacing: 2px">
          <span class="addtocalendar f6 grow no-underline br-pill ba ph3 pv2 mb2 dib white">
              <var class="atc_event">
                  <var class="atc_date_start">2018-12-15 12:00:00</var>
                  <var class="atc_date_end">2018-12-15 23:30:00</var>
                  <var class="atc_timezone">America/Chicago</var>
                  <var class="atc_title">Kathryn & Dushyant's Wedding</var>
                  <var class="atc_description">Kathryn &amp Dushyant are getting married!</var>
                  <var class="atc_location">Chicago, IL</var>
                  <var class="atc_organizer">Kathryn &amp Dushyant</var>
                  <var class="atc_organizer_email">roadtoremington@gmail.com</var>
              </var>
          </span>
         </div>
      </div>
    </article>
  </div>
  <script type="text/javascript">(function () {
      if (window.addtocalendar)if(typeof window.addtocalendar.start == "function")return;
      if (window.ifaddtocalendar == undefined) { window.ifaddtocalendar = 1;
          var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
          s.type = 'text/javascript';s.charset = 'UTF-8';s.async = true;
          s.src = 'https://addtocalendar.com/atc/1.5/atc.min.js';
          var h = d[g]('body')[0];h.appendChild(s); }})();
  </script>
</body>

app/views/static_pages/hotel_blocks.html.erb
<% provide(:title, "Kat & Dush") %>
<body class="" id="rsvp">
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
    <p class="pv4-l center pl4">
      <span style="font-size:70px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>

  <div class="ma5 tc">
    <hr>
    <h1>Hotel block info coming soon!</h1>
</body>

app/views/static_pages/our_family.html.erb
<% provide(:title, 'Us') %>
<body class="bg-washed-red baskerville tc">
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
    <p class="pv4-l center pl4">
      <span style="font-size:70px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>
  <div class="tc ma5 pa5 avenir">
      <hr>
      <h1 class="tc upcase">Introducing the Remington's</h1>
        <p>First, we appreciate your taking the time to join us in the creation of our family! As many have noticed, we have decided that in <i>creating our more perfect union</i>, we will be choosing an entirely new last name. This reflects our egalitarian relationship but also our desire to have a unified family name.</p>

        <p><b>Remington</b> is the maiden name of Kathryn's maternal grandmother, whom you will all meet at the wedding festivities, and thus has a lot of importance to Kathryn and Dushyant</p>

        <p>If you have any questions, please don't hesitate to ask!</p>
  </div>
</body>

app/views/static_pages/registry.html.erb
<% provide(:title, "Kat & Dush") %>
<body>
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
  </div>
    <p class="pv4-l center pl4">
      <span style="font-size:60px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>

  <div class="ma5 tc">
    <hr>
    <h1 class="tc">Registry coming soon! </h1>
</body>

app/views/static_pages/rsvp.html.erb
<% provide(:title, "Kat & Dush") %>
<body class="" id="rsvp">
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
    <p class="pv4-l center pl4">
      <span style="font-size:60px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>

  <div class="ma5 tc">
    <hr>
    <h1> RSVP</h1>
    <p> We're so glad you can attend! Please check back in August to RSVP after we send out the official invites </p>
</body>

app/views/static_pages/schedule_of_events.html.erb
<head>
    <div class="">
      <p class="ma3">
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
      </p>
    </div>
</head>

<body>
  <div class="pa3 ma3">
    <h1>Buckle up, it's gonna be a long ride!</h1>
    <p>We are incredibly lucky that we get to pull from TWO cultures in planning our wedding events! The following schedule reflects all of the events that go into a Christian-Hindu fushion wedding. </p>
    <p>Please note that some events are for family only and are noted as such! If there is no designation, you're invited and we hope you can join us!</p>

    <h3>Friday</h3>

    Mendhi (Bridal Party & Family only): 2 E Oak St Party Room 10AM

    Rehersal at University of Chicago's Rockefellar Chapel (Family &amp Wedding Party only)
    Happy hour at {}: 8PM

    <h3>Saturday</h3>

    <p>Ceremony: 12pm-1pm University of Chicago Rockefellar Chapel</p>

    <p>Reception: 6pm Cocktail Hour and Reception Ovation</p>

    <p>Transportation: </p>

    <p>Ceremony: The chapel is located about .75 miles from the 55th-56th-57th Metra Electric Metra train line, as well as accessible via Uber/Lyft. If using Uber, please carpool and use the code {} for x dollars off of your trip. Parking is also available HERE.</p>

    <p>Reception: Buses will be provided to and from HOTEL and will leave from X-Y every 30 minutes and return back to the hotel from X-Y every 30 minutes.</p>

    <h3>Sunday</h3>
  </div>
</body>

app/views/static_pages/things_to_do.html.erb
<head>
    <div class="dtc-l v-mid f6 f5-m f4-l measure-l">
      <p class="measure pv4-l center">
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
      </p>
    </div>
</head>
<h1>Welcome to Chicago!</h1>

app/views/static_pages/wedding_party.html.erb
<% provide(:title, "Kat & Dush") %>
<body class="" id="weddingParty">
  <div style="float:left" class="courier dtc-l v-mid f6 f5-m f4-l measure-l">
    <p class="pv4-l center pl4">
      <span style="font-size:70px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </p>
  </div>
  <div class="ma5">
    <hr>
    <h1 id="weddingPartyHeader" class="tc upcase">Bridal Party</h1>
    <div id="weddingPartyNames-container">
      <p id="weddingPartyNames">
		<div class="pl5 fl">
			  <h3>Kathryn's Attendants</h3>
				<ul class="" style="list-style: none;">
					<li>Maid of Honor: Madison Smith</li>
					<li>Bridesmaid: Ellen Killian Loughlin</li>
					<li>Bridesmaid: Jenna Hreshko Canovali</li>
					<li>Bridesmaid: Kelsey Young Lumbra</li>
					<li>Bridesmaid: Hannah Inayoshi</li>
					<li>Bridesmaid: Ahalya Srikant</li>
				</ul>
		</div>

		<div class="fr pr5">
			  <h3>Dushyant's Attendants</h3>
				<ul style="list-style: none;">
					<li>Best Man: Daniel Brim</li>
					<li>Groomsman: Josh Ferguson</li>
					<li>Groomsman: Samun Khalilian</li>
					<li>Groomsman: Trevor Levy</li>
					<li>Groomsman: Santosh Nandhan</li>
					<li>Groomsman: Patrick Smith</li>
				</ul>
		</div>
  </div>
</body>